# Generated by Django 4.2 on 2023-04-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('major', models.CharField(choices=[('Introduction to Computing', 'Introduction to Computing'), ('Computer Programming', 'Computer Programming'), ('Data Structure and Algorithm', 'Data Structure and Algorithm'), ('Science Technology and Society', 'Science Technology and Society'), ('Networking I', 'Networking I')], max_length=50)),
                ('contactnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectcode', models.CharField(max_length=50)),
                ('subjectname', models.CharField(max_length=50)),
                ('instructorname', models.CharField(max_length=50, null=True)),
                ('schedule', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=3)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=20)),
                ('yearlevel', models.CharField(choices=[('1stYear', '1st Year'), ('2ndYear', '2nd Year'), ('3rdYear', '3rd Year'), ('4thYear', '4th Year')], default='1stYear', max_length=20)),
                ('lrn', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('contactnumber', models.BigIntegerField()),
                ('subjects', models.ManyToManyField(blank=True, to='enrollmentsystems.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='enrollmentsystems.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollmentsystems.subject')),
            ],
        ),
    ]
