# Generated by Django 4.2 on 2023-04-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentsystems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollmentsystems.instructor'),
        ),
    ]
