# Generated by Django 4.2 on 2023-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollmentsystems', '0002_enrollment_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
