# Generated by Django 4.1.7 on 2023-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=1)),
                ('dateofbirth', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('yearlevel', models.CharField(choices=[('1st Year', '1stYear'), ('2nd Year', '2ndYear'), ('3rd Year', '3rdYear'), ('4th Year', '4thYear')], default='1st Year', max_length=20)),
                ('lrn', models.IntegerField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('subjects', models.CharField(choices=[('SUBJECT 1', 'Introduction to Computing'), ('SUBJECT 2', 'Computer Programming'), ('SUBJECT 3', 'Data Structure and Algorithm'), ('SUBJECT 4', 'Science Technology and Society'), ('SUBJECT 5', 'Networking I')], default='SUBJECT 1', max_length=50)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('contactnumber', models.IntegerField(max_length=50)),
            ],
        ),
    ]
