# Generated by Django 4.1.7 on 2023-03-09 11:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_enrollment_contactnumber_alter_enrollment_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SUBJECT 1', 'Introduction to Computing'), ('SUBJECT 2', 'Computer Programming'), ('SUBJECT 3', 'Data Structure and Algorithm'), ('SUBJECT 4', 'Science Technology and Society'), ('SUBJECT 5', 'Networking I')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='suffix',
            field=models.CharField(max_length=3),
        ),
    ]
