# Generated by Django 4.1.7 on 2023-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_enrollment_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='contactnumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='lrn',
            field=models.BigIntegerField(),
        ),
    ]
