# Generated by Django 4.1.7 on 2023-04-13 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_enrollment_contactnumber_alter_enrollment_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(1, 'Introduction to Computing'), (2, 'Computer Programming'), (3, 'Data Structure and Algorithm'), (4, 'Science Technology and Society'), (5, 'Networking I')], max_length=4), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='yearlevel',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20),
        ),
    ]
